//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Face.WebAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuMaster
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Enabled { get; set; }
        public int Position { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public string Icon { get; set; }
        public string FunctionID { get; set; }
        public string Url { get; set; }
    
        public virtual FunctionMaster FunctionMaster { get; set; }
    }
}
