//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Face.WebAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModuleMaster()
        {
            this.FunctionMasters = new HashSet<FunctionMaster>();
        }
    
        public string ID { get; set; }
        public string ApplicationID { get; set; }
        public string Name { get; set; }
    
        public virtual ApplicationMaster ApplicationMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FunctionMaster> FunctionMasters { get; set; }
    }
}
