//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Face.WebAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionSummary
    {
        public System.Guid ID { get; set; }
        public string TranxType { get; set; }
        public string ClientID { get; set; }
        public System.DateTime RecordedDate { get; set; }
        public int Total { get; set; }
    }
}
