//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Face.WebAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public System.Guid GroupID { get; set; }
    
        public virtual GroupMaster GroupMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
